version: '3'
services:
    api:
      build: .
      depends_on:
      - postgres
      ports:
          - 8000:8000
      volumes:
          - ./:/usr/src/app:ro
      command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

      # env_file:
      #     - ./.env
      environment:
          - DATABASE_USERNAME=postgres
          - DATABASE_PASSWORD= password123
          - DATABASE_HOSTNAME=postgres
          - DATABASE_NAME=fastapi
          - DATABASE_PORT=5432
          - SECRET_KEY=JoySilas@100BukunmiEmmanuelKiwamu@95ToluwalopeAdeboyeKoreKoredeOmoteye@100@AlfredaAmandaChiomaPeace
          - ALGORITHM=HS256
          - ACCESS_TOKEN_MINUTES=60

    postgres:
      image: postgres

      environment:
          - POSTGRES_PASSWORD= password123
          - POSTGRES_DB=fastapi
      volumes:
          - postgres-db:/var/lib/postgresql/data

volumes:
      postgres-db:    

      








        