name: Build and Deploy Code

on: [push,pull_request]

jobs: 
  job1:
    environment:
      name: testing

    env:
      DATABASE_USERNAME: ${{secret.DATABASE_USERNAME}}
      DATABASE_PASSWORD: ${{secret.DATABASE_PASSWORD}}
      DATABASE_HOSTNAME: ${{secret.DATABASE_HOSTNAME}}
      DATABASE_NAME: ${{secret.DATABASE_NAME}}
      DATABASE_PORT: ${{secret.DATABASE_PORT}}
      SECRET_KEY: ${{secret.SECRET_KEY}}
      ALGORITHM: ${{secret.ALGORITHM}}
      ACCESS_TOKEN_MINUTES: ${{secret.ACCESS_TOKEN_MINUTES}}
      
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v3
      - name: Python installation on our machine
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Update Pip
        run: python -m pip install --upgrade pip
      - name: Install all dependencies from Requirements.txt
        run: pip install -r requirements.txt 
      - name: Test with pytest
        run: |
          pip install pytest
          pytest -v -s


